version: "3.8"
   
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:7777"  
    volumes:
      - .:/code
    ports:
      - "7777:7777"
    container_name: chatdrf

volumes:
  postgres_data:
  media_volume:
  static_volume: