# Generated by Django 4.1.5 on 2023-01-05 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_chat', to=settings.AUTH_USER_MODEL, verbose_name='Чат от пользователя')),
                ('to_chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_chat', to=settings.AUTH_USER_MODEL, verbose_name='Чат к пользователю')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('created', models.TimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_id', to='chats.chat', verbose_name='ID чата')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_from_user', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение от пользователя')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение к пользователю')),
            ],
            options={
                'verbose_name': 'Сообщение в чате',
                'verbose_name_plural': 'Сообщение в чатах',
            },
        ),
    ]
