# Generated by Django 4.1.5 on 2023-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитан'),
        ),
    ]
