# Generated by Django 4.1.5 on 2023-01-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_message_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='created_at',
        ),
    ]
