# Generated by Django 4.1.5 on 2023-01-06 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Последняя активность'),
            preserve_default=False,
        ),
    ]
